### PR TITLE
Make lhs and thisProduction change to csharp and python

### PR DESCRIPTION
**Pull request by adMartem**
I would have just merged these myself, but I don't really have a way to test them. They do pass the standard "ant test" on my (macOS AArch64 Java 17) machine.  I also made a slight addition to the Jason.ccc to serve as a regression test.

### CODE REVIEW

**Comment by adMartem** [comment]
Well, something is wrong with the Python change, but I'm not sure how to debug it (or even if I could), so I will just leave this for someone with a python-brain to look over, if possible.

**Comment by revusky** [comment]
> I would have just merged these myself, but I don't really have a way to test them.

It's not very hard to get the python tests working. Basically, you need a Python3 installed. It's probably installed your mac by default, but if not, it's `brew install python3`, I suppose. AND you need to have a jython.jar in your $HOME/bin directory. And then `ant test-python` should work. As for the CSharp tests... well... I have never succeeded in getting them working locally. And really, I have to take that up with Vinay. The whole situation is not terribly good. These tests really should just all work.

**Comment by revusky** [comment]
Well, I guess we just merge this and I'll see what I can do about the Python side.

**Comment by adMartem** [comment]
I should be finished installing python in a few minutes.

**Comment by revusky** [comment]
It's not try-catch in python. It's try-except. But correcting that doesn't fix it. It gets further in the tests, but still fails.

**Pull request merged**
