### PR TITLE
Possible fix to ParserException NPE (only Java considered)

### PR DESCRIPTION
**Pull request by adMartem**
It doesn't look to me like CSharp and Python suffer from this problem, but then again, to me, reading them is like reading Danish using high school German knowledge.  This fix takes the "fix the observed problem" blunt object approach.  It wouldn't hurt my feelings if you have a higher-level solution.

### CODE REVIEW

**Comment by stbischof** [comment]
Maybe use Optional as return value for
- token.getImage()
- token.getType()

**Comment by revusky** [comment]
> Maybe use Optional as return value for
> 
> * token.getImage()
> * token.getType()
> * token.getNext()

Thanks for the suggestion, but I tend to think that in this case, at least for token.getType(), the better solution to the NPE issue is just to make sure that the getType method never returns null. So what I did was define an extra DUMMY token type such that if none is set, it returns that. But it never returns null. See: https://github.com/congo-cc/congo-parser-generator/blob/main/src/templates/java/Token.java.ftl#L55

**Comment by revusky** [comment]
Thanks. I decided to resolve this a different way, by introducing a DUMMY token type so that getType() never returns null. This problem doesn't actually apply to Python or CSharp because this is all part of a grand refactoring that is only, for now, being done on the Java side -- though, come to think of it, this business with the DUMMY token type, I'll probably apply that change to the Python/CSharp templates.  And actually, by the way, I feel the same way you do about mucking with the Python/CSharp stuff. That side is actually Vinay's work. But I try to make sure that the existing tests all work.

**Comment by revusky** [comment]
I guess this can be closed. Thanks.

**Pull request closed without merging**
