### PR TITLE
Fix undefined ref in Lexer

### PR DESCRIPTION
**Pull request by adMartem**
I think this is needed (or something similar) for the latest refactoring.

### CODE REVIEW

**Comment by revusky** [comment]
Thanks. I was initially puzzled by this but then I finally saw that this will fail to compile if we have token actions.

**Comment by revusky** [comment]
And it also just occurred to me that I probably had a bit of test coverage for this (and some other things) in JavaCC 21, because there were all these legacy examples that were in the old syntax that I kept around as testcases, but I just threw them away when I did the Congo migration, so there were a few things here and there that those old things were testing, that I don't have any tests for now. Probably the solution is to write some tutorial material that covers some of these things and then use the examples as test cases, try to kill two birds with one stone...

**Comment by adMartem** [comment]
Yes, it was a token action that caused me to run into this.  I removed almost all the token actions when I converted from lexer state changes to parser control of that, but at least one remained because the parser control in that instance didn't work for some reason I can't remember.

**Comment by revusky** [comment]
Well, it's a good thing that you had some token actions. They should work. So, thanks again. I think the issues you were running into yesteray are fixed. You can give that a try.

**Pull request merged**
